# Generated by Django 4.1.7 on 2023-03-07 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_client_created_at_client_edited_at_loan_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='loan_amount',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('Processing', 'Processing'), ('Active', 'Active'), ('Complited', 'Complited')], max_length=255),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.IntegerField(default=''),
        ),
    ]
